name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "master" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: 'Which version of docs to deploy, including space-separated tags (e.g. "0.95 latest", "1.0 dev")'
        required: true
        default: '1.0 dev'
        type: string

env:
  DEFAULT_VERSION: '1.0 dev'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all commits/branches

      # Set git user 
      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
        
      # Runs a set of commands using the runners shell
      - name: Run Mike
        run: |
          pip install -r requirements.txt
          mike deploy ${{ inputs.version || env.DEFAULT_VERSION }} -u -p